" This is the main file that loads up the other configuration files.
if has('win32') || has ('win64')
	let $VIMHOME = $HOME."/vimfiles"
else
	let $VIMHOME = $HOME."/.vim"
endif

source $VIMHOME/bundles.vim
source $VIMHOME/main.vim

