source /usr/local/share/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundles <<EOBUNDLES
git
z
nvm
command-not-found
EOBUNDLES

# # Bundles from the github.
antigen bundles <<EOBUNDLES
zsh-users/zsh-completions
zsh-users/zsh-syntax-highlighting
felixr/docker-zsh-completion
EOBUNDLES

# 
# Load the theme.
# antigen theme jreese
antigen theme fino-time

# Tell antigen that you're done.
antigen apply

## setting virtualenv workpath.
#export WORKON_HOME=$HOME/.virtualenvs
#
# ensure all new environments are isolated from the site-packages directory
#export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
#
## use the same directory for virtualenvs as virtualenvwrapper
#export PIP_VIRTUALENV_BASE=$WORKON_HOME
#
## makes pip detect an active virtualenv and install to it
#export PIP_RESPECT_VIRTUALENV=true
#
#if [[ -r /usr/local/bin/virtualenvwrapper.sh ]]; then
#source /usr/local/bin/virtualenvwrapper.sh
#else
#echo "WARNING: Can't find virtualenvwrapper.sh"
#fi

# This loads nvm
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# This loads rvm
export PATH="$PATH:$HOME/.rvm/bin" 
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm
